apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-registration-app-set
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/maemmanu/acm-argocd.git
        revision: HEAD
        directories:
          - path: acm-register-cluster/clusters/*
  template:
    metadata:
      namespace: openshift-gitops
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - "clusters/{{path.basename}}/values.yaml"
            - "clusters/values.yaml"
        path: acm-register-cluster
        repoURL: https://github.com/maemmanu/acm-argocd.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
      destination:
        server: https://kubernetes.default.svc