apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-registration-app-set
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/maemmanu/acm-argocd.git
        revision: HEAD
        files:
          - path: acm-register-cluster/values-*.yaml
  template:
    metadata:
      namespace: openshift-gitops
      name: '{{clusterName}}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - 'values-{{clusterName}}.yaml'
            - 'values{{extraLabels.env}}.yaml'
        path: acm-register-cluster
        repoURL: https://github.com/maemmanu/acm-argocd.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
      destination:
        server: https://kubernetes.default.svc