apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-registration-app-set
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/maemmanu/acm-argocd.git
        revision: test-git-file-generator
        files:
          - path: acm-register-cluster/clusters/values*.yaml
  template:
    metadata:
      namespace: openshift-gitops
      name: "{{clusterName}}"
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - "values-{{clusterName}}.yaml"
            - "values.yaml"
        path: acm-register-cluster
        repoURL: https://github.com/maemmanu/acm-argocd.git
        targetRevision: test-git-file-generator
      syncPolicy:
        automated:
          selfHeal: true
      destination:
        server: https://kubernetes.default.svc