apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST-CSF
  name: policy-check-ingress
  namespace: default
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-ingress-deployment
        spec:
          namespaceSelector:
            include:
              - openshift-ingress-operator
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: IngressController
                status:
                  conditions:
                    - status: 'False'
                      type: DeploymentAvailable
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-ingress-lb-ready
        spec:
          namespaceSelector:
            include:
              - openshift-ingress-operator
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: IngressController
                status:
                  conditions:
                    - status: 'True'
                      type: LoadBalancerManaged
                    - status: 'False'
                      type: LoadBalancerReady
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-ingress-degraded
        spec:
          namespaceSelector:
            include:
              - openshift-ingress-operator
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: IngressController
                status:
                  conditions:
                    - status: 'True'
                      type: Degraded
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-ingress-dns
        spec:
          namespaceSelector:
            include:
              - openshift-ingress-operator
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: IngressController
                status:
                  conditions:
                    - status: 'False'
                      type: DNSReady
          remediationAction: inform
          severity: low
  remediationAction: inform