apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST-CSF
  name: policy-check-pdb
  namespace: default
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-pdb-nodisrruption-allowed
        spec:
          namespaceSelector:
            include:
              - '*'
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: policy/v1
                kind: PodDisruptionBudget
                status:
                  disruptionsAllowed: 0
          remediationAction: inform
          severity: low
  remediationAction: inform
