apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST-CSF
  name: policy-checkclusteroperator
  namespace: default
spec:
  disabled: {{ .Values.disabled_upgrade }}
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-checkclusteroperator-available
        spec:
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterOperator
                status:
                  conditions:
                    - status: 'False'
                      type: Available
          remediationAction: inform
          severity: low
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-checkclusteroperator-degraded
        spec:
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterOperator
                status:
                  conditions:
                    - status: 'True'
                      type: Degraded
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-checkclusteroperator-progressing
        spec:
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterOperator
                status:
                  conditions:
                    - status: 'True'
                      type: Progressing
          remediationAction: inform
          severity: low
  remediationAction: inform