env: 
  dev:
    healthcheckpolicies:
      - cert-expiration
      - policy-check-etcd
      - policy-check-pdb
      - policy-check-ingress
      - policy-check-upgrade
      - policy-checkclusteroperator
      - policy-checkcsr
      - policy-checknodes
      - policy-checkpodstatus
      - policy-event-openshift-components
      - policy-event
      - policy-machine-notrunning
  test:
    healthcheckpolicies:
      - cert-expiration
      - policy-check-etcd
      - policy-check-pdb
      - policy-check-ingress
      - policy-check-upgrade
      - policy-checkclusteroperator
      - policy-checkcsr
      - policy-checknodes
      - policy-checkpodstatus
      - policy-event-openshift-components
      - policy-event
      - policy-machine-notrunning
  prod:
    healthcheckpolicies:
      - cert-expiration
      - policy-check-etcd
      - policy-check-pdb
      - policy-check-ingress
      - policy-check-upgrade
      - policy-checkclusteroperator
      - policy-checkcsr
      - policy-checknodes
      - policy-checkpodstatus
      - policy-event-openshift-components
      - policy-event
      - policy-machine-notrunning