apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-ingress-controller
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53, NIST-CSF
    policy.open-cluster-management.io/categories: CM Configuration Management, PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration, PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-ingress-controller-anz
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: IngressController
                metadata:
                  name: anz
                  namespace: openshift-ingress-operator
                spec:
                  domain: anz.cluster-4w6jt.4w6jt.sandbox315.opentlc.com
                  routeSelector:
                    matchLabels:
                      router: anz
                  endpointPublishingStrategy:
                    type: LoadBalancerService
                  nodePlacement:
                    nodeSelector:
                      matchLabels:
                        node-role.kubernetes.io/infra: ""

