apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day2-policies
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: policies-day2
    repoURL: https://github.com/maemmanu/acm-argocd.git
    targetRevision: HEAD