apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.clusterName }}
  labels:
    cluster.open-cluster-management.io/managedCluster: {{ .Values.clusterName }}
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "1"
