apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .Values.clusterName }}
  labels:
    cloud: auto-detect
    vendor: auto-detect
    environment: {{ .Values.label.env | default "dev" }}
    operational: {{ .Values.label.operational | default "alpha" }}
    region: {{ .Values.label.region | default "none" }}
    netpol: {{ .Values.label.netpol | default "false" }}
spec:
  hubAcceptsClient: true
