apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .Values.clusterName }}
  labels:
    cloud: auto-detect
    vendor: auto-detect
    environment: {{ .Values.environment | default "dev" }}
    operational-status: {{ .Values.operational-status | default "alpha" }}
    region: {{ .Values.region | default "not-defined" }}
    netpols: {{ .Values.netpols | default "false" }}
spec:
  hubAcceptsClient: true
