apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .Values.clusterName }}
  labels:
    cloud: auto-detect
    vendor: auto-detect
    environment: {{ .Values.env }}
    {{- with .Values.labels }}
    operational-status: {{ .operational-status | default "test" | quote }}
    {{- end }}
spec:
  hubAcceptsClient: true
