apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .Values.clusterName }}
  labels:
    cloud: auto-detect
    vendor: auto-detect
    {{- range .Values.labels}}
    {{ .  }}
    {{- end }}
spec:
  hubAcceptsClient: true
