apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .Values.clusterName }}
  labels:
        {{- toYaml .Values.labels | nindent 8 }}
spec:
  hubAcceptsClient: true
