{{- range $key, $value := .Values.env }}
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: policyset-helatcheck-{{ $key }}
  namespace: default
spec:
  policies:
    - test-policy
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policyset-healthcheck-pb-{{ $key }}
  namespace: default
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: policyset-pr-{{ $key }}
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: policyset-helatcheck-{{ $key }}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: policyset-pr-{{ $key }}
  namespace: default
spec:
  clusterConditions:
  - status: "True"
    type: ManagedCLusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: environment 
        operator: In
        values:
          - {{ $key }}
      - key: health-check-disabled 
        operator: In
        values:
          - false
{{- end }}