{{- range $key, $value := .Values.env }}
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: policyset-day2-{{ $key }}
  namespace: default
spec:
  policies:
  {{- range $policy := $value.day2policies }}  
  - {{ $policy }}
  {{- end }}
---
{{- end }}