{{- range $key, $value := .Values.env }}
{{- if $value.day2policies -}}
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: policyset-helathcheck-{{ $key }}
  namespace: default
spec:
  policies:
  {{- range $policy := $value.healthcheckpolicies }}  
  - {{ $policy }}
  {{- end }}
---
{{- end }}
{{- end }}
