{{- range $key, $value := .Values.env }}
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: policyset-helatcheck-{{ $key }}
  namespace: default
spec:
  policies:
  {{- range $key, $value := $value.healthcheck-policies }}
  - {{ . }}
  {{- end }}
---
{{- end }}

