{{ range .Values.env }}
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: policyset-helatcheck-{{ .name }}
spec:
  policies:
{{ range .healthcheck-policies }}
- {{ . }}
{{ end }}

---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policyset-healthcheck-pb
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: policyset-pr-{{ .name }}
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: policyset-helatcheck-{{ .name }}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: policyset-pr-{{ .name }}
spec:
  clusterConditions:
  - status: "True"
    type: ManagedCLusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: environment 
        operator: In
        values:
          - {{ .name }}
      - key: health-check-disabled 
        operator: In
        values:
          - false
{{ end }}