apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management-op-group
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  targetNamespaces:
  - open-cluster-management
